.TH NIOS2-SH 1 "October 2018" "nios2-sh 0.0.1" "User Commands"

.SH NAME
.PP
nios2-sh - run an interactive NIOSII command shell

.SH SYNOPSIS
.PP
.B nios2-sh
[version | help | quartus version]

.SH DESCRIPTION
.B nios2-sh launches the current user's login shell within a NIOSII command
shell environment. The appropriate installation of Altera Quartus is located
using nios2-search.

.SH OPTIONS

.IP version
Display the version number and exit.

.IP help
Display the synopsis and exit.

.IP "quartus version"
Specify a Quartus version, such as '17', which is used to select an appropriate
Quartus installation via nios2-search. If this is omitted, then the output of
nios2-search --get is used to select a default installation.

.SH CHANGELOG
.IP 0.0.1
Initial version.

.SH COPYRIGHT
(c) 2018 Charles A. Daniels
