.TH TAGDUMP "1" "October 2018" "tagdump " "User Commands"

.SH NAME
tagdump - dump tag information from media files

.SH SYNOPSIS
tagdump [\-h] [\-\-input INPUT]
[\-\-tag_filter [TAG_FILTER [TAG_FILTER ...]]] [\-\-version]
[files [files ...]]

.SH DESCRIPTION
.PP
Dump tag information from pytaglib for the specified (files). Data is dumped
in YAML format. Note that if stdin is not a tty, each line of input on it will
be treated as a file to dump tags for. This is useful for pipes.
.SS "positional arguments:"
.TP
files
List of files to dump tags for
.SS "optional arguments:"
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-\-input\fR INPUT, \fB\-i\fR INPUT
A file to read where each line is a file to dump tags
for.
.TP
\fB\-\-tag_filter\fR [TAG_FILTER [TAG_FILTER ...]], \fB\-t\fR [TAG_FILTER [TAG_FILTER ...]]
Only tags listed here are sent to output. If
unspecified, all tags are shown.
.TP
\fB\-\-version\fR
show program's version number and exit

.SH CHANGELOG

.IP 0.0.1
Initial version.

.SH COPYRIGHT

(c) 2018 Charles A. Daniels, All Rights Reserved.
